update tf>=2.0 enhanced with NMT with attention.
LiberAI/NSpM pull request #50
Opened 2021-03-25 19:13 UTC by ashutosh16399

Hi, please review and merge.

2021-03-26 10:36 UTC, mommi84 approved these changes

2021-03-28 17:44 UTC, mommi84 requested changes
The code looks good. In the future, I would like to make the `EPOCHS` constant in `train.py` a parameter that the user can set via command line.

Please restore the following missing files by pushing them to the `en_NspM` branch.
```
.gitignore
LICENSE
analyse.py
generator_test.py
split_in_train_dev_test.py
```

2021-03-29 03:55 UTC, ashutosh16399 commented
Hi, @mommi84  
analyse.py
generator_test.py
split_in_train_dev_test.py 
i saw these files, currently, they are not included in the pipeline, I will add these files for now and include them later in the pipeline as well.

2021-03-29 17:04 UTC, mommi84 approved these changes

2021-03-29 17:20 UTC, merged